#!/usr/bin/env bash

set -o errexit
set -o verbose

export DEBIAN_FRONTEND=noninteractive

apt-get update && apt-get install -y -q --on-install-recommends \
  libtool \
  automake \
  pkg-config \
  make \
  git \
  g++ \
  binutils-dev \
  libboost-test-dev
